---
# This playbook get junos info
- name: Get Device Facts
  hosts: dc1
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
  - name: Retrieve information from devices running Junos OS
    junos_get_facts:  host={{ inventory_hostname }}         
    register: junos
  - name: version
    debug: msg="{{ junos.facts.version }}"
